# Generated by Django 5.2.5 on 2025-09-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cntent',
            new_name='content',
        ),
    ]
